###############################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

portal:
  enabled: true
  # -- Set your local frontend to integrate into local development.
  portalAddress: "http://portal.tx.test"
  # -- Set your local backend service to integrate into local development.
  # Start port forwarding tunnel for database access, e.g.:
  # 'kubectl port-forward service/local-portal-backend-postgresql 5432:5432 -n umbrella'
  portalBackendAddress: "http://portal-backend.tx.test"
  centralidp:
    address: "http://centralidp.tx.test"
  sharedidpAddress: "http://sharedidp.tx.test"
  semanticsAddress: "http://semantics.tx.test"
  bpdm:
    poolAddress: "http://business-partners.tx.test"
    portalGateAddress: "http://business-partners.tx.test"
  custodianAddress: "http://managed-identity-wallets.tx.test"
  sdfactoryAddress: "http://sdfactory.tx.test"
  clearinghouseAddress: "http://validation.tx.test"
  clearinghouseTokenAddress: "http://keycloak.tx.test/realms/example/protocol/openid-connect/token"
  clearinghouseConnectDisabled: false
  issuerComponentAddress: "http://ssi-credential-issuer.tx.test"
  bpnDidResolver:
    managementApiAddress: "http://bpn-did-resolution-service-bdrs-server:8081"
    directoryApiAddress: "http://bpn-did-resolution-service.tx.test/api/directory"
  dimWrapper:
    baseAddress: "http://dim-wrapper.tx.test"
  decentralIdentityManagementAuthAddress: "http://dim.tx.test"
  replicaCount: 1
  readinessProbes:
    initialDelaySeconds: 200
  frontend:
    portal:
      requireHttpsUrlPattern: false
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        # uncomment the following line for tls
        # cert-manager.io/cluster-issuer: "my-ca-issuer"
        nginx.ingress.kubernetes.io/rewrite-target: "/$1"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://*.tx.test"
      # uncomment the following lines for tls
      # tls:
      #   # -- Provide tls secret.
      #   - secretName: "portal.tx.test-tls"
      #     # -- Provide host for tls secret.
      #     hosts:
      #       - "portal.tx.test"
      hosts:
        - host: "portal.tx.test"
          paths:
            - path: "/(.*)"
              pathType: "ImplementationSpecific"
              backend:
                service: "portal"
                port: 8080
            - path: "/registration/(.*)"
              pathType: "ImplementationSpecific"
              backend:
                service: "registration"
                port: 8080
            - path: "/((assets|documentation)/.*)"
              pathType: "ImplementationSpecific"
              backend:
                service: "assets"
                port: 8080
  backend:
    dotnetEnvironment: "Development"
    useDimWallet: true
    keycloak:
      central:
        clientId: "sa-cl1-reg-2"
        clientSecret: "changeme"
        jwtBearerOptions:
          requireHttpsMetadata: "false"
      shared:
        clientId: "sa-cl1-reg-1"
        clientSecret: "changeme"
    registration:
      logging:
        default: "Debug"
        bpdmLibrary: "Debug"
        registrationService: "Debug"
      swaggerEnabled: true
    administration:
      logging:
        default: "Debug"
        businessLogic: "Debug"
        sdfactoryLibrary: "Debug"
        bpdmLibrary: "Debug"
        custodianLibrary: "Debug"
      serviceAccount:
        encryptionConfigs:
          index0:
            encryptionKey: "deb8261ec7b89c344f1c5ef5a11606e305f14e0d231b1357d90ad0180c5081d3"
      issuerdid: "did:web:tx.test:test123"
      swaggerEnabled: true
    appmarketplace:
      logging:
        default: "Debug"
        offersLibrary: "Debug"
      swaggerEnabled: true
      resources:
        # requests:
        #   cpu: 15m
        #   memory: 445M
        limits:
          memory: 600M
    services:
      logging:
        default: "Debug"
        offersLibrary: "Debug"
      swaggerEnabled: true
    notification:
      logging:
        default: "Debug"
      swaggerEnabled: true
      # resources:
      #   requests:
      #     cpu: 15m
      #     memory: 300M
      #   limits:
      #     memory: 300M
    processesworker:
      logging:
        default: "Debug"
        processesLibrary: "Debug"
        bpdmLibrary: "Debug"
        clearinghouseLibrary: "Debug"
        custodianLibrary: "Debug"
        sdfactoryLibrary: "Debug"
        offerProvider: "Debug"
      bpdm:
        clientId: "sa-cl7-cx-5"
        clientSecret: "changeme"
      # -- no configuration for clearinghouse because it's an external component
      # clientId and clientSecret aren't in the centralidp Keycloak
      # clearinghouse:
      #   clientId: "clearinghouse-client-id"
      #   clientSecret: ""
      custodian:
        clientId: "sa-cl5-custodian-2"
        clientSecret: "changeme"
      sdfactory:
        issuerBpn: "BPNL00000003CRHK"
        clientId: "sa-cl8-cx-1"
        clientSecret: "changeme"
      offerprovider:
        clientId: "sa-cl2-03"
        clientSecret: "changeme"
      dim:
        clientId: "dim-client-id"
        clientSecret: ""
        universalResolverAddress: "https://dev.uniresolver.io/"
        encryptionConfigs:
          index0:
            encryptionKey: "6cbaf47ee30c778088e6faa44e2f0eed98beda86db06c7d2e37e32ab78e14b33"
      issuerComponent:
        clientId: "sa-cl2-04"
        clientSecret: "changeme"
      bpnDidResolver:
        # -- ApiKey for management endpoint of the bpnDidResolver. Secret-key 'bpndidresolver-api-key'.
        apiKey: ""
      onboardingServiceProvider:
        encryptionConfigs:
          index0:
            cipherMode: "CBC"
            paddingMode: "PKCS7"
            encryptionKey: "f7bc3d99f1ace73e7a75b794affbbc26206ab29909821a102aaccb2e95e45f7c"
          index1:
            encryptionKey: "8027152fe7a869c88acc86981760acd70ff1d660c2bd129eece94edef933caf7"
      invitation:
        encryptionConfigs:
          index0:
            encryptionKey: "d84fea29d6eac0fa51e36682b164e7d61693cd4202ed04306d2d9c5d46655e2c"
      mailing:
        encryptionConfigs:
          index0:
            encryptionKey: "d2e27d71b018cb36029184852f1baa3e26891be94718f77de4c7cc6c882fe317"
    mailing:
      host: "smtp.tx.test"
      port: "587"
      user: "smtp-user"
      senderEmail: "smtp@tx.test"
      password: ""
    portalmigrations:
      logging:
        default: "Debug"
      resources:
        limits:
          cpu: 200m
    provisioningmigrations:
      logging:
        default: "Debug"
      resources:
        limits:
          cpu: 150m
    provisioning:
      sharedRealm:
        smtpServer:
          host: "smtp.tx.test"
          port: "587"
          user: "smtp-user"
          password: ""
          from: "smtp@tx.test"
          replyTo: "smtp@tx.test"
    # -- docs: http://portal-backend.tx.test/api/administration/swagger/index.html
    # http://portal-backend.tx.test/api/registration/swagger/index.html
    # http://portal-backend.tx.test/api/apps/swagger/index.html
    # http://portal-backend.tx.test/api/services/swagger/index.html
    # http://portal-backend.tx.test/api/notification/swagger/index.html
    ingress:
      enabled: true
      name: "portal-backend"
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "8m"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, http://*.tx.test"
      hosts:
        - host: "portal-backend.tx.test"
          paths:
            - path: "/api/registration"
              pathType: "Prefix"
              backend:
                service: "registration-service"
                port: 8080
            - path: "/api/administration"
              pathType: "Prefix"
              backend:
                service: "administration-service"
                port: 8080
            - path: "/api/notification"
              pathType: "Prefix"
              backend:
                service: "notification-service"
                port: 8080
            - path: "/api/provisioning"
              pathType: "Prefix"
              backend:
                service: "provisioning-service"
                port: 8080
            - path: "/api/apps"
              pathType: "Prefix"
              backend:
                service: "marketplace-app-service"
                port: 8080
            - path: "/api/services"
              pathType: "Prefix"
              backend:
                service: "services-service"
                port: 8080
  postgresql:
    nameOverride: "portal-backend-postgresql"
    architecture: standalone
    auth:
      password: "dbpasswordportal"
      portalPassword: "dbpasswordportal"
      provisioningPassword: "dbpasswordportal"

centralidp:
  enabled: true
  keycloak:
    nameOverride: "centralidp"
    replicaCount: 1
    auth:
      adminPassword: "adminconsolepwcentralidp"
    postgresql:
      nameOverride: "centralidp-postgresql"
      auth:
        password: "dbpasswordcentralidp"
        postgresPassword: "dbpasswordcentralidp"
    proxy: edge
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "centralidp.tx.test"
      annotations:
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://centralidp.tx.test"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
        nginx.ingress.kubernetes.io/use-regex: "true"
      tls: false
  realmSeeding:
    sslRequired: "none"
    clients:
      registration:
        redirects:
          - http://portal.tx.test/*
          - http://localhost:3000/*
      portal:
        rootUrl: http://portal.tx.test/home
        redirects:
          - http://portal.tx.test/*
          - http://localhost:3000/*
      semantics:
        redirects:
          - http://portal.tx.test/*
      miw:
        clientSecret: "changeme"
        redirects:
          - http://managed-identity-wallets.tx.test/*
      bpdm:
        clientSecret: "changeme"
        redirects:
          - http://partners-pool.tx.test/*
      bpdmGate:
        clientSecret: "changeme"
        redirects:
          - http://partners-gate.tx.test/*
      bpdmOrchestrator:
        clientSecret: "changeme"
    serviceAccounts:
      clientSecrets:
        - clientId: "sa-cl1-reg-2"
          clientSecret: "changeme"
        - clientId: "sa-cl2-01"
          clientSecret: "changeme"
        - clientId: "sa-cl2-02"
          clientSecret: "changeme"
        - clientId: "sa-cl2-03"
          clientSecret: "changeme"
        - clientId: "sa-cl2-04"
          clientSecret: "changeme"
        - clientId: "sa-cl2-05"
          clientSecret: "changeme"
        - clientId: "sa-cl3-cx-1"
          clientSecret: "changeme"
        - clientId: "sa-cl5-custodian-2"
          clientSecret: "changeme"
        - clientId: "sa-cl7-cx-1"
          clientSecret: "changeme"
        - clientId: "sa-cl7-cx-5"
          clientSecret: "changeme"
        - clientId: "sa-cl7-cx-7"
          clientSecret: "changeme"
        - clientId: "sa-cl8-cx-1"
          clientSecret: "changeme"
        - clientId: "sa-cl21-01"
          clientSecret: "changeme"
        - clientId: "sa-cl22-01"
          clientSecret: "changeme"
        - clientId: "sa-cl24-01"
          clientSecret: "changeme"
        - clientId: "sa-cl25-cx-1"
          clientSecret: "changeme"
        - clientId: "sa-cl25-cx-2"
          clientSecret: "changeme"
        - clientId: "sa-cl25-cx-3"
          clientSecret: "changeme"
    bpn: "BPNL00000003CRHK"
    sharedidp: "http://sharedidp.tx.test"

sharedidp:
  enabled: true
  keycloak:
    nameOverride: "sharedidp"
    replicaCount: 1
    auth:
      adminPassword: "adminconsolepwsharedidp"
    postgresql:
      nameOverride: "sharedidp-postgresql"
      auth:
        password: "dbpasswordsharedidp"
        postgresPassword: "dbpasswordsharedidp"
    proxy: edge
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "sharedidp.tx.test"
      annotations:
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://sharedidp.tx.test"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
        nginx.ingress.kubernetes.io/use-regex: "true"
      tls: false
  realmSeeding:
    realms:
      cxOperator:
        sslRequired: "none"
        centralidp: "http://centralidp.tx.test"
        initialUser:
          username: "cx-operator@tx.test"
          password: "tractusx-umbr3lla!"
        mailing:
          host: "smtp.tx.test"
          port: "587"
          username: "smtp-user"
          password: ""
          from: "smtp@tx.test"
          replyTo: "smtp@tx.test"
      master:
        serviceAccounts:
          provisioning:
            clientSecret: "changeme"
          saCxOperator:
            clientSecret: "changeme"

postgresportal:
# -- Additional PostgreSQL for backend development;
  # start port forwarding tunnel for database access, e.g.:
  # 'kubectl port-forward service/local-portal-postgresql 5432:5432 -n umbrella'
  enabled: true
  nameOverride: "portal-postgresql"
  auth:
    database: "postgres"
    port: 5432
    existingSecret: "secret-postgres-init-localdev"
    portalUser: "portal"
    provisioningUser: "provisioning"
    password: "dbpasswordadditional"
    portalPassword: "dbpasswordadditional"
    provisioningPassword: "dbpasswordadditional"
  architecture: "standalone"
  audit:
    pgAuditLog: "write, ddl"
    logLinePrefix: "%m %u %d "
  primary:
    initdb:
      scriptsConfigMap: "configmap-postgres-init-localdev"
    extraEnvVars:
      - name: "PORTAL_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.auth.existingSecret }}"
            key: "portal-password"
      - name: "PROVISIONING_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.auth.existingSecret }}"
            key: "provisioning-password"

pgadmin4:
  enabled: true
  env:
    email: pgadmin4@txtest.org
    password: tractusxpgdamin4
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: pgadmin4.tx.test
        paths:
        - path: /
          pathType: Prefix
