{{- /*
* Copyright (c) 2024 Contributors to the Eclipse Foundation
*
* See the NOTICE file(s) distributed with this work for additional
* information regarding copyright ownership.
*
* This program and the accompanying materials are made available under the
* terms of the Apache License, Version 2.0 which is available at
* https://www.apache.org/licenses/LICENSE-2.0.
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*
* SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.backend.portalmigrations.seeding.useInitial -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  "{{ include "portal.fullname" . }}-initial-data"
  namespace: {{ .Release.Namespace }}
data:
  addresses.json: |-
    [
      {
        "id": "b4db3945-19a7-4a50-97d6-e66e8dfd04fb",
        "date_created": "2022-03-24 18:01:33.306000 +00:00",
        "date_last_changed": "2022-03-24 18:01:33.306000 +00:00",
        "city": "{{ .Values.operator.city }}",
        "region": "{{ .Values.operator.region }}",
        "streetadditional": "{{ .Values.operator.streetAdditional }}",
        "streetname": "{{ .Values.operator.streetName }}",
        "streetnumber": "{{ .Values.operator.streetNumber }}",
        "zipcode": "{{ .Values.operator.zipCode }}",
        "country_alpha2code": "{{ .Values.operator.country_alpha2code }}"
      }
    ]
  companies.json: |-
    [
      {
        "id": "2dc4249f-b5ca-4d42-bef1-7a7a950a4f87",
        "date_created": "2022-03-24 18:01:33.306000 +00:00",
        "business_partner_number": "{{ .Values.operator.bpn }}",
        "name": "{{ .Values.operator.name }}",
        "shortname": "{{ .Values.operator.shortname }}",
        "company_status_id": 2,
        "address_id": "b4db3945-19a7-4a50-97d6-e66e8dfd04fb",
        "self_description_document_id": "00000000-0000-0000-0000-000000000009"
      }
    ]
{{- end }}
