###############################################################
# Copyright (c) 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.keycloak.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
# use lookup function to check if secret exists
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.backend.keycloak.secret) }}
{{ if $secret -}}
data:
  # if secret exists, use value provided from values file (to cover update scenario) or existing value from secret
  # use data map instead of stringData to prevent base64 encoding of already base64-encoded existing value from secret
  # use index function for secret keys with hyphen otherwise '$secret.data.secretKey' works too
  central-client-secret: {{ ( .Values.backend.keycloak.central.clientSecret | b64enc ) | default ( index $secret.data "central-client-secret" ) | quote }}
  shared-client-secret: {{ ( .Values.backend.keycloak.shared.clientSecret | b64enc ) | default ( index $secret.data "shared-client-secret" ) | quote }}
{{ else -}}
stringData:
  # if secret doesn't exist, use provided value from values file or generate a random one
  central-client-secret: {{ .Values.backend.keycloak.central.clientSecret | default ( randAlphaNum 32 ) | quote }}
  shared-client-secret: {{ .Values.backend.keycloak.shared.clientSecret | default ( randAlphaNum 32 ) | quote }}
{{ end }}
